// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDate;
use chrono::NaiveDateTime;
use uuid::Uuid;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(sku_id, prod_att_option_id))]
pub struct AttributeOptionSku {
    pub sku_id: Uuid,
    pub prod_att_option_id: Uuid,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BaseUser {
    pub id: Uuid,
    pub name: String,
    pub lastname: String,
    pub email: String,
    pub password: String,
    pub hash: String,
    pub birthdate: NaiveDate,
    pub created: Option<NaiveDateTime>,
    pub modified: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Buyer {
    pub id: Uuid,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Category {
    pub id: String,
    pub name: Option<String>,
    pub parent: Option<String>,
    pub depth: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(category_id, product_id))]
pub struct CategoryProduct {
    pub category_id: String,
    pub product_id: Uuid,
}

#[derive(Queryable, Debug)]
pub struct CustomerAddres {
    pub id: Uuid,
    pub customer_id: Uuid,
    pub street1: String,
    pub street2: Option<String>,
    pub postal_code: String,
    pub city: String,
    pub province: String,
}

#[derive(Queryable, Debug)]
pub struct Product {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub summary: Option<String>,
    pub cover: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct ProductAttribute {
    pub id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct ProductAttributesCategory {
    pub id: i32,
    pub product_att_id: Option<Uuid>,
    pub category_id: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct ProductAttributesOption {
    pub id: Uuid,
    pub attribute_id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct ProductSku {
    pub id: Uuid,
    pub product_id: Uuid,
    pub sku: String,
    pub stock: i32,
}

#[derive(Queryable, Debug)]
pub struct Seller {
    pub id: Uuid,
    pub rating: i32,
    pub store_name: String,
}

