use crate::schema::*;
use diesel::prelude::*;
// Generated by diesel_ext

//#![allow(unused)]
//#![allow(clippy::all)]


use chrono::NaiveDate;
use chrono::NaiveDateTime;
use uuid::Uuid;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = attribute_option_sku)]
#[diesel(primary_key(sku_id, prod_att_option_id))]
pub struct AttributeOptionSku {
    pub sku_id: Uuid,
    pub prod_att_option_id: Uuid,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = base_user)]
pub struct BaseUser {
    pub id: Uuid,
    pub name: String,
    pub lastname: String,
    pub email: String,
    pub password: String,
    pub hash: String,
    pub birthdate: NaiveDate,
    pub created: Option<NaiveDateTime>,
    pub modified: Option<NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = base_user)]
pub struct NewBaseUser<'a> {
    pub id:&'a Uuid,
    pub name:&'a str,
    pub lastname:&'a str,
    pub email:&'a str,
    pub password:&'a str,
    pub hash:&'a str,
    pub birthdate: &'a NaiveDate,
    //pub created: &'a NaiveDateTime,
    //pub modified: &'a NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = buyer)]
pub struct Buyer {
    pub id: Uuid,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = category)]
pub struct Category {
    pub id: String,
    pub name: Option<String>,
    pub parent: Option<String>,
    pub depth: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(category_id, product_id))]
#[diesel(table_name = category_product)]
pub struct CategoryProduct {
    pub category_id: String,
    pub product_id: Uuid,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = customer_address)]
pub struct CustomerAddress {
    pub id: Uuid,
    pub customer_id: Uuid,
    pub street1: String,
    pub street2: Option<String>,
    pub postal_code: String,
    pub city: String,
    pub province: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product)]
pub struct Product {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub summary: Option<String>,
    pub cover: Option<String>,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes)]
pub struct ProductAttributes {
    pub id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes_category)]
pub struct ProductAttributesCategory {
    pub id: i32,
    pub product_att_id: Option<Uuid>,
    pub category_id: Option<String>,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes_option)]
pub struct ProductAttributesOption {
    pub id: Uuid,
    pub attribute_id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_sku)]
pub struct ProductSku {
    pub id: Uuid,
    pub product_id: Uuid,
    pub sku: String,
    pub stock: i32,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = seller)]
pub struct Seller {
    pub id: Uuid,
    pub rating: i32,
    pub store_name: String,
}

