use crate::schema::*;
use bigdecimal::BigDecimal;
use diesel::prelude::*;
// Generated by diesel_ext

//#![allow(unused)]
//#![allow(clippy::all)]
use chrono::NaiveDate;
use chrono::NaiveDateTime;
use diesel::sql_types::Integer;
use diesel::pg::sql_types::Jsonb;
use serde::Deserialize;
use serde::Serialize;
use uuid::Uuid;
use serde_json::Value;
use ipnet::IpNet;

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = base_user)]
pub struct BaseUser {
    pub id: Uuid,
    pub name: String,
    pub lastname: String,
    pub email: String,
    pub password: String,
    pub birthdate: NaiveDate,
    pub created: Option<NaiveDateTime>,
    pub modified: Option<NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = base_user)]
pub struct NewBaseUser<'a> {
    pub id:&'a Uuid,
    pub username:&'a str,
    pub name:&'a str,
    pub lastname:&'a str,
    pub email:&'a str,
    pub password:&'a str,
    pub birthdate: &'a NaiveDate,
    //pub created: &'a NaiveDateTime,
    //pub modified: &'a NaiveDateTime,
}
#[derive(Insertable)]
#[diesel(table_name = base_user)]
pub struct NewBaseUserSimple<'a> {
    pub id:&'a Uuid,
    pub username:&'a str,
    pub email:&'a str,
    pub password:&'a str
    //pub created: &'a NaiveDateTime,
    //pub modified: &'a NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = buyer)]
pub struct Buyer {
    pub id: Uuid,
}

#[derive(serde::Serialize)]
#[derive(Queryable, Debug, Identifiable,Clone,Selectable)]
#[diesel(table_name = category)]
#[derive(QueryableByName)]
pub struct Category {
    pub id: String,
    pub name: String,
    pub parent: Option<String>,
    pub depth: Option<i32>,
    pub base_specs: Option<Value>,
    pub is_parent: bool,
}

impl Category {
    pub fn to_category2(&self) -> Result<Category2, &'static str> {
        Ok(Category2 {
            id: self.id.clone(),
            //name: self.name.clone().ok_or("Missing name")?,
            name: self.name.clone(),
            parent: self.parent.clone().unwrap_or_default(),
            depth: self.depth.unwrap_or(0),
            base_specs: self.base_specs.clone().unwrap_or(Value::Null),
            is_parent: self.is_parent,
        })
    }
}


#[derive(serde::Serialize)]
#[derive(Clone,Debug)]
pub struct Category2 {
    pub id: String,
    pub name: String,
    pub parent: String,
    pub depth: i32,
    pub base_specs: Value,
    pub is_parent: bool,
}

//consulta solo del JsonB
#[derive(Queryable)]
#[diesel(table_name = category)]
#[derive(QueryableByName)]
pub struct BaseSpecs {
    pub base_specs: Option<Value>,
}



#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(category_id, product_id))]
#[diesel(table_name = category_product)]
pub struct CategoryProduct {
    pub category_id: String,
    pub product_id: Uuid,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = customer_address)]
pub struct CustomerAddress {
    pub id: Uuid,
    pub customer_id: Uuid,
    pub street1: String,
    pub street2: Option<String>,
    pub postal_code: String,
    pub city: String,
    pub province: String,
}

/// La dirección se inserta en el mismo POST que confirma el pedido, para que no
/// queden filas huérfanas si el pedido se cae. Ver la migración
/// 2026-09-01-192454_orders: `orders` guarda además una COPIA de estos campos.
#[derive(Insertable)]
#[diesel(table_name = customer_address)]
pub struct NewCustomerAddress<'a> {
    pub id: &'a Uuid,
    pub customer_id: &'a Uuid,
    pub street1: &'a str,
    pub street2: Option<&'a str>,
    pub postal_code: &'a str,
    pub city: &'a str,
    pub province: &'a str,
}

#[derive(Queryable, Debug, Deserialize,Serialize,Selectable)]
#[diesel(table_name = products)]
pub struct Products {
    pub id: Uuid,
    pub code : String,
    pub name: String,
    pub description: String,
    pub brand: String,
    pub status: i16,
    pub specs: Value,
    pub variations: Option<Value>,
    pub variation_titles: Option<Value>,
    pub images: Option<Value>,
    pub published: bool,    
}

#[derive(Deserialize, Debug)]
pub struct ProductForm{
    pub code : String,
    pub name: String,
    pub description: String,
    pub brand: String,
    pub specs: Value,
    pub variations: Option<Value>,
    pub images: Option<Value>,
    pub price: BigDecimal,
}

#[derive(Insertable)]
#[diesel(table_name = products)]
pub struct NewProduct<'a> {
    pub id: &'a Uuid,
    pub code : &'a str,
    pub name: &'a str,
    pub description: &'a str,
    pub brand: &'a str,
    pub specs: &'a Value,
    pub variations:  Option<&'a Value>,
    pub variation_titles:  Option<&'a Value>,
    pub images:Option<&'a Value>,
}

#[derive(Queryable, Debug, Deserialize,Serialize,Selectable)]
#[diesel(table_name = product_variations)]
pub struct ProductVariation {
    pub id: Uuid,
    pub product_id : Uuid,
    pub identifiers: Option<Value>,
    pub sku: Option<String>,
    pub attributes: Option<Value>,
    pub status: i16,
    pub stock: i32,
    pub images: Option<Value>,
} 

#[derive(Insertable)]
#[diesel(table_name = product_variations)]
pub struct NewProductVariation1<'a> {
    pub id: &'a Uuid,
    pub product_id : &'a Uuid,
    //pub identifiers: Option<&'a Value>,
    //pub sku: Option<&'a str>,
    pub attributes: Option<&'a Value>,
    //pub stock: &'a i32,
    //pub images: Option<&'a Value>,
}



#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes)]
pub struct ProductAttributes {
    pub id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes_category)]
pub struct ProductAttributesCategory {
    pub id: i32,
    pub product_att_id: Option<Uuid>,
    pub category_id: Option<String>,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes_option)]
pub struct ProductAttributesOption {
    pub id: Uuid,
    pub attribute_id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_sku)]
pub struct ProductSku {
    pub id: Uuid,
    pub product_id: Uuid,
    pub sku: String,
    pub stock: i32,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = seller)]
pub struct Seller {
    pub id: Uuid,
    pub rating: i32,
    pub store_name: String,
}

#[derive(Insertable)]
#[diesel(table_name = prices)]
pub struct NewPrice<'a> {
    pub variation_id:&'a Uuid,
    pub price:&'a BigDecimal,
    pub currency:&'a str,
    pub start_date:&'a NaiveDateTime,
}

//No meter mas derive en esas cosas
#[derive(Queryable, Debug)]
#[diesel(table_name = prices)]
pub struct Price {
    pub id: i32,
    pub variation_id: Uuid,
    pub price: BigDecimal,
    pub currency: String,
    pub start_date: NaiveDateTime
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_variations_identifiers)]
pub struct IdentifierVariation {
    pub id: i32,
    pub product_variation_id: Uuid,
    pub identifier: String,
    pub value: String,
}

#[derive(Insertable)]
#[diesel(table_name = images_product)]
pub struct NewImageProduct<'a> {
    pub id:&'a Uuid,
    pub product_id:&'a Uuid,
    pub image_url:&'a str,
    pub is_main:&'a bool,
    pub display_order:&'a i32,
}
#[derive(Insertable)]
#[diesel(table_name = images_product)]
pub struct NewImageProduct2 {
    pub id:Uuid,
    pub product_id:Uuid,
    pub image_url:String,
    pub is_main:bool,
    pub display_order:i32,
}

#[derive(Insertable)]
#[diesel(table_name = product_variations_identifiers)]
pub struct NewIdentifierVariation<'a> {
    pub product_variation_id:&'a Uuid,
    pub identifier:&'a str,
    pub value: &'a str,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = discounts)]
pub struct Discounts {
    pub id:i32,
    pub variation_id:Uuid,
    pub discount_type:i16,
    pub percentage: Option<BigDecimal>,
    pub quantity: Option<i32>,
    pub discount_value:BigDecimal,
    pub currency: String,
    pub start_date: Option<NaiveDateTime>,
    pub end_date: Option<NaiveDateTime>,
    pub created_at: NaiveDateTime,
}

#[derive(Insertable)]
#[diesel(table_name = discounts)]
pub struct NewDiscount<'a> {
    pub variation_id:&'a Uuid,
    pub discount_type:&'a i16,
    pub percentage: Option<&'a BigDecimal>,
    pub quantity: Option<&'a i32>,
    pub discount_value: &'a BigDecimal,
    pub currency: &'a str,
    pub start_date: Option<&'a NaiveDateTime>,
    pub end_date: Option<&'a NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = discount_history)]
pub struct NewDiscountHistory<'a> {
    pub variation_id:&'a Uuid,
    pub discount_type:&'a i16,
    pub percentage: Option<&'a BigDecimal>,
    pub quantity: Option<&'a i32>,
    pub discount_value: &'a BigDecimal,
    pub currency: &'a str,
    pub start_date: Option<&'a NaiveDateTime>,
    pub end_date: Option<&'a NaiveDateTime>,
    pub created_at: &'a NaiveDateTime
}

#[derive(Queryable, Serialize, Deserialize, Debug, Clone)]
pub struct UserAuth {
    pub id:Uuid,
    pub username: String,
    pub name: Option<String>,
    pub lastname: Option<String>,
    pub email: String,
    pub password: String,
}

#[derive(Insertable)]
#[diesel(table_name = user_sessions)]
pub struct NewUserSession<'a> {
    pub id:&'a Uuid,
    pub user_id:&'a Uuid,
    pub jti:&'a str,
    pub refresh_token_hash: &'a str,
    pub issued_at: &'a NaiveDateTime,
    pub expires_at: &'a NaiveDateTime,
    pub last_used_at: &'a NaiveDateTime,
    pub is_revoked: &'a bool,
    pub ip_address: Option<&'a IpNet>,
    pub user_agent: Option<&'a str>,
    pub device_info: Option<&'a str>,
}
#[derive(Queryable, Debug,Identifiable)]
#[diesel(table_name = user_sessions)]
pub struct UserSession {
    pub id: Uuid,
    pub user_id: Uuid,
    pub jti: String,
    pub refresh_token_hash: String,
    pub issued_at: NaiveDateTime,
    pub expires_at: NaiveDateTime,
    pub last_used_at: NaiveDateTime,
    pub is_revoked: bool,
    pub ip_address: Option<ipnet::IpNet>, // Usa ipnet::IpNet
    pub user_agent: Option<String>,
    pub device_info: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Insertable)]
#[diesel(table_name = user_sessions)]
pub struct NewUserSession2{
    pub id:Uuid,
    pub user_id:Uuid,
    pub jti:String,
    pub refresh_token_hash: String,
    pub issued_at: NaiveDateTime,
    pub expires_at: NaiveDateTime,
    pub last_used_at: NaiveDateTime,
    pub is_revoked: bool,
    pub ip_address: Option<IpNet>,
    pub user_agent: Option<String>,
    pub device_info: Option<String>,
}
/* 
#[derive(Queryable, Debug,QueryableByName)]
pub struct ProductCard1{
    pub id:Uuid,
    pub name :String,
    pub brand : String,
    pub image_url : String,
    pub price : BigDecimal,
    pub currency : String,
    pub store_name : String,
    pub store_id : Uuid
}
*/
// ---- Cart models ----
#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = carts)]
pub struct Cart {
    pub id: Uuid,
    pub user_id: Uuid,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub status: i16,
}

#[derive(Insertable)]
#[diesel(table_name = carts)]
pub struct NewCart<'a> {
    pub id: &'a Uuid,
    pub user_id: &'a Uuid,
    pub status: i16,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = cart_products)]
pub struct CartProduct {
    pub id: Uuid,
    pub cart_id: Uuid,
    pub product_var_id: Uuid,
    pub quantity: i32,
    pub price_at_time_of_addition: Option<BigDecimal>,
    pub added_at: NaiveDateTime,
}

#[derive(Insertable)]
#[diesel(table_name = cart_products)]
pub struct NewCartProduct<'a> {
    pub id: &'a Uuid,
    pub cart_id: &'a Uuid,
    pub product_var_id: &'a Uuid,
    pub quantity: i32,
    pub price_at_time_of_addition: Option<&'a BigDecimal>,
}

// ---- Order models ----
// El pedido guarda copia de lo que se vendió y de a dónde se envió: los
// importes son los cobrados y no se recalculan. Ver la migración
// 2026-09-01-192454_orders.
#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = orders)]
pub struct Order {
    pub id: Uuid,
    pub order_number: i64,
    pub user_id: Uuid,
    pub cart_id: Option<Uuid>,
    pub status: i16,
    pub currency: String,
    pub subtotal: BigDecimal,
    pub discount_total: BigDecimal,
    pub shipping_total: BigDecimal,
    pub total_amount: BigDecimal,
    pub shipping_address_id: Option<Uuid>,
    pub ship_street1: String,
    pub ship_street2: Option<String>,
    pub ship_postal_code: String,
    pub ship_city: String,
    pub ship_province: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

// Sin order_number, created_at ni updated_at: los pone la base de datos.
#[derive(Insertable)]
#[diesel(table_name = orders)]
pub struct NewOrder<'a> {
    pub id: &'a Uuid,
    pub user_id: &'a Uuid,
    pub cart_id: Option<&'a Uuid>,
    pub status: i16,
    pub currency: &'a str,
    pub subtotal: &'a BigDecimal,
    pub discount_total: &'a BigDecimal,
    pub shipping_total: &'a BigDecimal,
    pub total_amount: &'a BigDecimal,
    pub shipping_address_id: Option<&'a Uuid>,
    pub ship_street1: &'a str,
    pub ship_street2: Option<&'a str>,
    pub ship_postal_code: &'a str,
    pub ship_city: &'a str,
    pub ship_province: &'a str,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = order_items)]
pub struct OrderItem {
    pub id: Uuid,
    pub order_id: Uuid,
    pub product_var_id: Uuid,
    pub product_name: String,
    pub variation_label: Option<String>,
    pub sku: Option<String>,
    pub image_url: Option<String>,
    pub store_name: Option<String>,
    pub unit_price: BigDecimal,
    pub currency: String,
    pub quantity: i32,
    pub line_total: BigDecimal,
}

#[derive(Insertable)]
#[diesel(table_name = order_items)]
pub struct NewOrderItem<'a> {
    pub id: &'a Uuid,
    pub order_id: &'a Uuid,
    pub product_var_id: &'a Uuid,
    pub product_name: &'a str,
    pub variation_label: Option<&'a str>,
    pub sku: Option<&'a str>,
    pub image_url: Option<&'a str>,
    pub store_name: Option<&'a str>,
    pub unit_price: &'a BigDecimal,
    pub currency: &'a str,
    pub quantity: i32,
    pub line_total: &'a BigDecimal,
}

use diesel::sql_types::{Uuid as SqlUuid, Text, Nullable, Numeric,SmallInt,Bool,Json};
use diesel::prelude::QueryableByName;

#[derive(QueryableByName, Serialize, Deserialize, Debug, Clone)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ProductCard1 {
    #[diesel(sql_type = SqlUuid)]
    pub id: Uuid,
    #[diesel(sql_type = Nullable<Text>)]
    pub name: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub brand: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub image_url: Option<String>,
    #[diesel(sql_type = Nullable<Numeric>)]
    pub price: Option<BigDecimal>,
    #[diesel(sql_type = Nullable<Text>)]
    pub currency: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub store_name: Option<String>,
    #[diesel(sql_type = Nullable<SqlUuid>)]
    pub store_id: Option<Uuid>,
}
#[derive(QueryableByName, Serialize, Deserialize, Debug, Clone)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ProductWithImages1{
    #[diesel(sql_type = SqlUuid)]
    pub id: Uuid,
    #[diesel(sql_type = Nullable<Text>)]
    pub code: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub name: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub description: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub brand: Option<String>,
    #[diesel(sql_type = Nullable<SmallInt>)]
    pub status: Option<i16>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub specs: Option<Value>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub variations: Option<Value>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub variation_titles: Option<Value>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub images: Option<Value>,
    #[diesel(sql_type = Nullable<Bool>)]
    pub published: Option<bool>,
    #[diesel(sql_type = Nullable<Json>)]
    pub images_product: Option<Value>
}

#[derive(QueryableByName, Serialize, Deserialize, Debug, Clone)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ProductForPage1{
    #[diesel(sql_type = SqlUuid)]
    pub id: Uuid,
    #[diesel(sql_type = Nullable<Text>)]
    pub name: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub brand: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub description: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub currency: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub store_name: Option<String>,
    #[diesel(sql_type = Nullable<SqlUuid>)]
    pub store_id: Option<Uuid>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub images_product: Option<Value>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub variant_map: Option<Value>,
    #[diesel(sql_type = Nullable<Jsonb>)]
    pub variations_with_stock_status: Option<Value>
}

#[derive(QueryableByName, Serialize, Deserialize, Debug, Clone)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct CartItem1{
    #[diesel(sql_type = SqlUuid)]
    pub id: Uuid,
    #[diesel(sql_type = SqlUuid)]
    pub product_var_id: Uuid,
    #[diesel(sql_type = SqlUuid)]
    pub product_id: Uuid,
    #[diesel(sql_type = Nullable<Text>)]
    pub name: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub variation_label: Option<String>,
    /// Referencia de la variación. El carrito no la pinta; está aquí porque el
    /// snapshot de `order_items` la guarda.
    #[diesel(sql_type = Nullable<Text>)]
    pub sku: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub image_url: Option<String>,
    #[diesel(sql_type = Nullable<Numeric>)]
    pub price: Option<BigDecimal>,
    #[diesel(sql_type = Nullable<Text>)]
    pub currency: Option<String>,
    #[diesel(sql_type = Nullable<Text>)]
    pub store_name: Option<String>,
    #[diesel(sql_type = Integer)]
    pub quantity: i32,
    #[diesel(sql_type = Integer)]
    pub stock: i32,
    #[diesel(sql_type = Nullable<Numeric>)]
    pub subtotal: Option<BigDecimal>
}
