use crate::schema::*;
use diesel::prelude::*;
// Generated by diesel_ext

//#![allow(unused)]
//#![allow(clippy::all)]
use chrono::NaiveDate;
use chrono::NaiveDateTime;
use serde::Deserialize;
use serde::Serialize;
use uuid::Uuid;
use serde_json::Value;


#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = base_user)]
pub struct BaseUser {
    pub id: Uuid,
    pub name: String,
    pub lastname: String,
    pub email: String,
    pub password: String,
    pub hash: String,
    pub birthdate: NaiveDate,
    pub created: Option<NaiveDateTime>,
    pub modified: Option<NaiveDateTime>,
}

#[derive(Insertable)]
#[diesel(table_name = base_user)]
pub struct NewBaseUser<'a> {
    pub id:&'a Uuid,
    pub name:&'a str,
    pub lastname:&'a str,
    pub email:&'a str,
    pub password:&'a str,
    pub hash:&'a str,
    pub birthdate: &'a NaiveDate,
    //pub created: &'a NaiveDateTime,
    //pub modified: &'a NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = buyer)]
pub struct Buyer {
    pub id: Uuid,
}

#[derive(serde::Serialize)]
#[derive(Queryable, Debug, Identifiable,Clone)]
#[diesel(table_name = category)]
#[derive(QueryableByName)]
pub struct Category {
    pub id: String,
    pub name: Option<String>,
    pub parent: Option<String>,
    pub depth: Option<i32>,
    pub base_specs: Option<Value>,
    pub is_parent: bool,
}

impl Category {
    pub fn to_category2(&self) -> Result<Category2, &'static str> {
        Ok(Category2 {
            id: self.id.clone(),
            name: self.name.clone().ok_or("Missing name")?,
            parent: self.parent.clone().unwrap_or_default(),
            depth: self.depth.unwrap_or(0),
            base_specs: self.base_specs.clone().unwrap_or(Value::Null),
            is_parent: self.is_parent,
        })
    }
}


#[derive(serde::Serialize)]
#[derive(Clone,Debug)]
pub struct Category2 {
    pub id: String,
    pub name: String,
    pub parent: String,
    pub depth: i32,
    pub base_specs: Value,
    pub is_parent: bool,
}

//consulta solo del JsonB
#[derive(Queryable)]
#[diesel(table_name = category)]
#[derive(QueryableByName)]
pub struct BaseSpecs {
    pub base_specs: Option<Value>,
}



#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(category_id, product_id))]
#[diesel(table_name = category_product)]
pub struct CategoryProduct {
    pub category_id: String,
    pub product_id: Uuid,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = customer_address)]
pub struct CustomerAddress {
    pub id: Uuid,
    pub customer_id: Uuid,
    pub street1: String,
    pub street2: Option<String>,
    pub postal_code: String,
    pub city: String,
    pub province: String,
}

#[derive(Queryable, Debug, Deserialize,Serialize)]
#[diesel(table_name = products)]
pub struct Products {
    pub id: Uuid,
    pub code : String,
    pub name: String,
    pub description: String,
    pub brand: String,
    pub status: i16,
    pub specs: Value,
    pub variations: Option<Value>,
    pub images: Option<Value>,
    pub published: bool,
}

#[derive(Deserialize, Debug)]
pub struct ProductForm{
    pub code : String,
    pub name: String,
    pub description: String,
    pub brand: String,
    pub specs: Value,
    pub variations: Option<Value>,
    pub images: Option<Value>,
}

#[derive(Insertable)]
#[diesel(table_name = products)]
pub struct NewProduct<'a> {
    pub id: &'a Uuid,
    pub code : &'a str,
    pub name: &'a str,
    pub description: &'a str,
    pub brand: &'a str,
    pub specs: &'a Value,
    pub variations:  Option<&'a Value>,
    pub images:Option<&'a Value>,
}

#[derive(Queryable, Debug, Deserialize,Serialize)]
#[diesel(table_name = product_variations)]
pub struct ProductVariation {
    pub id: String,
    pub product_id : Uuid,
    pub identifiers: Option<Value>,
    pub sku: Option<String>,
    pub attributes: Option<Value>,
    pub stock: i32,
    pub images: Option<Value>,
}

#[derive(Insertable)]
#[diesel(table_name = product_variations)]
pub struct NewProductVariation1<'a> {
    pub id: &'a Uuid,
    pub product_id : &'a Uuid,
    //pub identifiers: Option<&'a Value>,
    //pub sku: Option<&'a str>,
    pub attributes: Option<&'a Value>,
    //pub stock: &'a i32,
    //pub images: Option<&'a Value>,
}



#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes)]
pub struct ProductAttributes {
    pub id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes_category)]
pub struct ProductAttributesCategory {
    pub id: i32,
    pub product_att_id: Option<Uuid>,
    pub category_id: Option<String>,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_attributes_option)]
pub struct ProductAttributesOption {
    pub id: Uuid,
    pub attribute_id: Uuid,
    pub name: String,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = product_sku)]
pub struct ProductSku {
    pub id: Uuid,
    pub product_id: Uuid,
    pub sku: String,
    pub stock: i32,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = seller)]
pub struct Seller {
    pub id: Uuid,
    pub rating: i32,
    pub store_name: String,
}

